#server:
#  port: 8888
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      x-forwarded.host-enabled: true
#      routes:
#        - id: pms-route
#          uri: lb://pms-service
#          predicates:
#            - Path=/pms/**
#        - id: sms-route
#          uri: lb://sms-service
#          predicates:
#            - Path=/sms/**
#        - id: wms-route
#          uri: lb://wms-service
#          predicates:
#            - Path=/wms/**
#        - id: ums-route
#          uri: lb://ums-service
#          predicates:
#            - Path=/ums/**
#        - id: oms-route
#          uri: lb://oms-service
#          predicates:
#            - Path=/oms/**
#        - id: search-route        
#          uri: lb://search-service        
#          predicates:          
#            - Host=search.gmall.com
#        - id: item-route
#          uri: lb://item-service
#          predicates:
#            - Path=/item/**
#        - id: ums-route
#          uri: lb://ums-service
#          predicates:
#            - Path=/ums/**
#        - id: cart-route
#          uri: lb://cart-service
#          predicates:
#            - Host=cart.gmall.com
#auth:
#  jwt:
#    pubKeyPath: D:\\gulimall\\key\\rsa.pub # 公钥地址
#    cookieName: GMALL-TOKEN