server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://106.14.208.184:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 106.14.208.184
    password: kflk1994
  rabbitmq:
    host: 106.14.208.184
    port: 5672
    username: likunc
    password: kflk1994
    virtual-host: /gmall
    publisher-confirm-type: correlated
    publisher-returns: true
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto